[tools]
aws = "latest"
chezmoi = "latest"
glow = "latest"
go = "1.24.3"
golangci-lint = "v2.1.6"
hyperfine = "latest"
k6 = "latest"
node = "22.11"
"npm:cdktf-cli" = "latest"
sops = "latest"
usage = "latest"

"npm:@google/gemini-cli" = "latest"

[tasks."terraform:workspace:select"]
description = "fzf select terraform workspace"
alias = "tfws"
run = "terraform workspace list | fzf | tr -s '[:space:]' | xargs -r -I {} terraform workspace select {}"

[settings]
idiomatic_version_file_enable_tools = ["node"]

