set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "xterm-256color"
set -g mouse on
set -g history-limit 10000
set -g base-index 1
set -g set-titles on

set-option -g renumber-windows on

# bind prefix to CTRL-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# other bindings
bind K confirm kill-session
bind r source-file ~/.tmux.conf
bind C-y set-window-option synchronize-panes

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_current_number_color "#{@thm_green}"
set -ogq @catppuccin_application_color "#{E:@thm_yellow}"
set -ogq @catppuccin_gitmux_color "#{E:@thm_mauve}"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ga status-right "#{E:@catppuccin_status_gitmux}"

set -g status-interval 2

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

